repos:
  - repo: https://github.com/PYCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(src/|tests/)
        stages: [ commit ]
        args: ["--profile", "pycharm", "--filter-files", "--line-length=99"]

  - repo: https://github.com/PYCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(src/|tests/)
        stages: [ commit ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
