repos:
  - repo: https://github.com/PYCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: src tests
        stages: [ commit ]
        args: ["--profile", "pycharm", "--filter-files"]

  - repo: https://github.com/PYCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: src tests
        stages: [ commit ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
